### ISSUE TITLE
[IDEA] Release as a framework package? 

### ISSUE THREAD

**Issue by levibostian** [daveneff/Coordinator#2]
Hello, there! 

First off, I want to thank you, @daveneff, for creating this project. This is the 1 Coordinator example that (1) I fully understand and (2) see it working well for my projects. It's a relief to find such a great project. 

With that in mind, I plan to use the Navigator and the Coordinator files from this project in an existing app of mine to see how it goes. If everything goes well, I plan to use it in more projects. 

I like to download everything as cocoapod frameworks instead of copy/paste code so that way I can version control code easily and manage versions across many projects. 

With that in mind, would you see it beneficial to release this project as a cocoapods library? If not, I can release this myself in my personal github and link back to this project. 

Thanks, much!

**Comment by daveneff** [comment]
Hey @levibostian,

Thanks for reaching out, I'm really glad it's been helpful in understanding the pattern!

I'd definitely be happy to release it as a Cocoapod. Let me take a look this weekend and see if I can get something up and running!

**Comment by levibostian** [comment]
Thanks, @daveneff. I appreciate it! 

I have done a bit of cocoapods library development so, allow me to help if you need it. 

[This PR](https://github.com/daveneff/Coordinator/pull/3) should be a good starting point to get us going. I have not tested it, but I did `pod lib lint` and it passed so that's a good first sign! 

Off the top of my head, we need to:
0. Create a podspec file. Merge in the PR above or add the file manually to the project. To create the podspec, we will need to decide what to name the library. It must be a unique name not already taken in a [cocoapods search](https://cocoapods.org/). 
1. Create a github tag release in the repository for the version of the library to release. The podspec version and git tag version need to be the same. 
2. [Register with cocoapods trunk](https://guides.cocoapods.org/making/getting-setup-with-trunk.html)
3. `pod lib push`. Done! 

Thanks!

**Comment by levibostian** [comment]
It is also very easy to configure Travis CI for automated deployment. I have that setup with many of my projects if you're interested in that. I can add that to the PR and instruct you on that. 

If I'm doing too much, I can take a step back. I feel bad asking people for help simply to help me with my projects. Anything I can do for you to help, I am happy to do it!

**Comment by daveneff** [comment]
Hey @levibostian, I've gone ahead and updated everything -- should be good to go Cocoapods now. You can find it under the name `SwiftCoordinator`. I also [updated the API a little bit](https://github.com/daveneff/Coordinator/commit/b37bf9a4cc546aade90b43416a0ddb921ccd19db), so hopefully that doesn't interfere with anything you've already worked on :) 

I'm also going to close out #3 since I had to do additional work in preparing it for release, but I appreciate you submitting that PR! 

Let me know if it works out for you and I'll go ahead and close out this issue -- thanks!

**Comment by levibostian** [comment]
Awesome! Thanks!
