### ISSUE TITLE
Example for how to use Coordinator with TabBar

### ISSUE THREAD

**Issue by levibostian** [daveneff/Coordinator#4]
Hey there, 

I have enjoyed using this project in my app. Today, I encountered the situation of using this project with an app of mine that uses a `UITabBarController`. After some experimenting, I came up with a solution. 

I wanted to leave a link here for reference if anyone encounters the same issue. Since there are many ways to implement the Coordinator design pattern, I felt the need to share how I implemented a TabBar with this Coordinator project specifically. 

[Link to the project](https://github.com/levibostian/TabBar-Coordinator-example/)

Some ideas that I had for how to help others with this same issue:
* Close this issue as a reference someone can find later
* Link to the project in the readme of this project
* Include an example of using a TabBar in this project's code base

Thanks!

**Comment by daveneff** [comment]
Hey @levibostian,

Sorry again for the late response, but thanks for posting! Always appreciate a contribution to the community.

Just a thought on this -- an alternative to your approach could also be something like this:

```swift
final class AppCoordinator: PresentationCoordinator {

    var childCoordinators: [Coordinator] = []
    var rootViewController = AppRootViewController()

    private let boringCoordinator = BoringCoordinator()
    private let stackingCoordinator = StackingCoordinator()

    init(window: UIWindow) {
        window.rootViewController = rootViewController
        window.makeKeyAndVisible()
    }

    func start() {
        [boringCoordinator, stackingCoordinator].forEach {
            addChildCoordinator($0)
            $0.start()
        }

        let viewControllers = [boringCoordinator.rootViewController, stackingCoordinator.rootViewController]
        rootViewController.setViewControllers(viewControllers, animated: false)
    }

}
```

At least in my own projects, I like to ensure coordinators keep reference to view controllers, but never the other way around :) 

Anyhow, I'm going to close out this issue but happy to reopen if you or anyone would like to continue talking about approaches to `UITabBarController`s and coordinators. Thanks again for contributing 👍
